[package]
name = "axum-sqlx-tx"
description = "Request-scoped SQLx transactions for axum"
version = "0.5.0"
license = "MIT"
repository = "https://github.com/wasdacraic/axum-sqlx-tx/"
edition = "2021"
include = ["LICENSE", "README.md", "Cargo.toml", "**/*.rs"]

[features]
all-databases = ["any", "mssql", "mysql", "postgres", "sqlite"]
any = ["sqlx/any"]
mssql = ["sqlx/mssql"]
mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[package.metadata.docs.rs]
features = ["all-databases", "runtime-tokio-rustls"]

[dependencies]
async-trait = "0.1.58"
axum-core = "0.3.0"
bytes = "1.1.0"
futures-core = "0.3.21"
http = "0.2.6"
http-body = "0.4.4"
parking_lot = "0.12.0"
sqlx = { version = "0.6", default-features = false }
thiserror = "1.0.30"
tower-layer = "0.3.1"
tower-service = "0.3.1"

[dev-dependencies]
axum-sqlx-tx = { path = ".", features = ["runtime-tokio-rustls", "sqlite"] }
axum = "0.6.0"
hyper = "0.14.17"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["macros"] }
tower = "0.4.12"
